apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.nginx.replicaCount }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: {{ .Values.nginx.image.repo }}:{{ .Values.nginx.image.tag }}
        ports:
        - containerPort: 80
        imagePullPolicy: {{ .Values.nginx.pullPolicy }}
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
        env:
        - name: PREFIX
          value: {{ .Values.nginx.prefix }}
        volumeMounts:
        - name: index-html
          mountPath: /var/www/html/gitops/
      volumes:
      - name: index-html
        configMap:
          name: {{ .Release.Name }}
          items:
          - key: index
            path: index.html
